### ISSUE TITLE
Add further info to ReadMe

### ISSUE THREAD

**Issue by MikeZahorik** [RolandDreger/get-x-height#3]
Hi Roland,

Would you consider adding the information describing the script here on your website
https://www.rolanddreger.net/de/503/x-hoehe-ermittlen/

to your ReadMe file in English. Or a link to an English version is fine too. If you change the ReadMe, send a Pull request. If you update the linked files on your website, just let me know. 

Thanks
Mike

**Comment by RolandDreger** [comment]
I have now added some more descriptions to the Readme.md and sent a pull request.

Roland
